version: '3.7'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  redis:
    container_name: nextcloud-redis
    image: redis
    restart: always
    command: "redis-server --requirepass ${REDIS_HOST_PASSWORD}"
    volumes:
      - redis:/data

  #code-server:
  #  container_name: nextcloud-code
  #  image: collabora/code
  #  restart: always

  mautoolz:
    container_name: nextcloud-mautoolz
    image: nextcloud-mautoolz
    restart: always
    build:
      context: mautoolz

  mautoolz-convert:
    container_name: nextcloud-mautoolz-convert
    image: nextcloud-mautoolz-convert
    restart: always
    build:
      context: mautoolz-convert

  app:
    container_name: nextcloud
    image: nextcloud-kitty
    restart: always
    build:
      context: .
    volumes:
      - nextcloud:/var/www/html
      - /srv/transmission/downloads/complete:/torrent
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MAUTOOLZ_HOST=mautoolz
      - MAUTOOLZ_CONVERT_HOST=mautoolz-convert
    env_file:
      - .env
    depends_on:
      - db
      - redis
    #  - code-server
      - mautoolz
      - mautoolz-convert

volumes:
  db:
  nextcloud:
  redis:

networks:
  default:
    external:
      name: caddynet
