version: '3.7'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  redis:
    container_name: nextcloud-redis
    image: redis
    command: "redis-server --requirepass ${REDIS_HOST_PASSWORD}"
    restart: always
    volumes:
      - redis:/data

  mautoolz:
    container_name: nextcloud-mautoolz
    image: nextcloud-mautoolz
    build:
      context: mautoolz
    restart: always

  app:
    container_name: nextcloud
    image: nextcloud-kitty
    build:
      context: .
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MAUTILS_HOST=mautoolz
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mautils

volumes:
  db:
  nextcloud:
  redis:

networks:
  default:
    external:
      name: caddynet
