version: '3.7'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - nextcloud.env

  redis:
    container_name: nextcloud-redis
    image: redis
    restart: always
    volumes:
      - redis:/data

  app:
    container_name: nextcloud
    image: nextcloud-kitty
    build:
      context: .
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - nextcloud.env
    depends_on:
      - db

volumes:
  db:
  nextcloud:
  redis:

networks:
  default:
    external:
      name: caddynet
